INSERT INTO APARTMENT_BLOCK VALUES(1,'BLOCK-1','KATHMANDU');
INSERT INTO APARTMENT_BLOCK VALUES(2,'BLOCK-2','KATHMANDU');
INSERT INTO APARTMENT_BLOCK VALUES(3,'BLOCK-3','KATHMANDU');
INSERT INTO APARTMENT_BLOCK VALUES(4,'BLOCK-4','KATHMANDU');
INSERT INTO APARTMENT_BLOCK VALUES(5,'BLOCK-5','KATHMANDU');
INSERT INTO APARTMENT_BLOCK VALUES(6,'BLOCK-6','KATHMANDU');
INSERT INTO APARTMENT_BLOCK VALUES(7,'BLOCK-7','KATHMANDU');
INSERT INTO APARTMENT_BLOCK VALUES(8,'BLOCK-8','KATHMANDU');
INSERT INTO APARTMENT_BLOCK VALUES(9,'BLOCK-9','KATHMANDU');

